[functions]
included_files = ["content/**"]

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_CONTENTFUL_SPACE_ID = "mm85g2nwd1ln"
  NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN = "xO-J29EBqEtr3xR88u0IEFd-IW6RqjpdpzkTS0BUPyU"
